#ifndef LIBYSMM_CONFIG_H
#define LIBYSMM_CONFIG_H

#define LIBYSMM_VERSION_MAJOR @LIBYSMM_VERSION_MAJOR@

#define LIBYSMM_VERSION_MINOR @LIBYSMM_VERSION_MINOR@

#define LIBYSMM_VERSION_PATCH @LIBYSMM_VERSION_PATCH@

#define LIBYSMM_VERSION "@LIBYSMM_VERSION@"

#endif
